config/routes.rb
Rails.application.routes.draw do
 

  resources :courses
  resources :users
  resources :posts
  resources :students
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
	has_one :course
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
  	@students=Student.order(created_at: :desc).all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :comment)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
def show
		@student=Student.find(params[:id])
	end

	
def create
	Student.create(student_params)
	redirect_to(root_path)	
	
	end

def edit
	@student = Student.find(params[:id])

	
end	

def update
	 @post = Student.find(params[:id])
	if @post.update_attributes(student_params)
		redirect_to student_path(@post)
	end 
end

def destroy
	Student.destroy(params[:id])
	redirect_to(root_path)
end
private

	def student_params
		params.require(:student).permit(:Name,:DOB,:Phone_No,:email,:course)
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_edit_student_form.html.erb
 <div id="editstudentmodal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 id="modalTitle" class="modal-title">Edit Student</h4>
                </div>

                <%= form_for :students,url:'/students',html:{class:"form-horizontal"} do %>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label for="Name" class="col-sm-3" control-label">Name : </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="Name" placeholder="Name"
                                value="user_name">
                            </div>
                        </div>
                       
                        <div class="form-group row">
                          <label for="DOB" class="col-sm-3">DOB:</label>
                              <div class="col-sm-9">
                                <input class="form-control" type="date"  id="DOB">
                              </div>
                        </div>
                        

                         <div class="form-group">
                            <label for="Mobile" class="col-sm-3" control-label>Mobile No:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="Mobile" >
                            </div>
                        </div>

                         <div class="form-group">
                            <label for="email" class="col-sm-3" control-label>email:</label>
                            <div class="col-sm-9">
                                <input type="email" name="email" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Courses" class="col-sm-3">Courses:</label>
                            <div class="col-sm-9">
                              <select class="form-control" id="Courses" class="col-sm-9">
                                <option>JAVA</option>
                                <option>RUBY</option>
                                <option>.net</option>
                              </select>
                          </div>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <!-- <button id="btnSave" type="button" class="btn btn-primary">Save</button> -->
                  </div>
                <%end %>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

app/views/home/_navbar.html.erb
<!-- <nav class="navbar navbar-dark bg-dark">
  <span class="text-white bg-dark">
   Student Info Management System
  </span>
  <button type="button" class="btn btn-light" data-target="#myModal">Ask A Question</button>
  <div class="navbar-text" style="float: right;"></div>
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add  New Student  </button>
</nav>
 -->
<!-- 
 <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
		    <div class="container-fluid">
		        <ul class="nav navbar-nav navbar-left">
		        	<span class="active">
					   Student Info Management System
					</span>
		            <li class="active"><a href="/">Home</a></li>
		            <li><a href="#notices">Notices</a></li>
		            <li><a href="#issues">Issues</a></li>
		       		<li><a href="#employees">Employees</a></li>
		        </ul>
		        <ul class="nav navbar-nav navbar-right">
		        	<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#addstudentmodal">Add  New Student  </button>
 		
		        </ul>
		    </div>
		 </nav> -->

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <span style="color:white;font-size:30px;position: absolute;left: 500px;" >Student Info Management System</span>
    </div>
  
  </div>
</nav>

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel">New Question</h5>
	        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button> -->
	      </div>
	      <!-- <form class="form-horizontal" action="/question" method="POST"> -->
	      <%= form_for :questions,url:'/questions',html:{class:"form-horizontal"} do %>
	    
	      <div class="modal-body">

			    <div class="form-group">
			      <label class="control-label col-sm-2" for="email">Email:</label>
			      <div class="col-sm-10">
			        <input type="email" class="form-control" id="email" placeholder="Enter email" >
			      </div>
			    </div>
			     <div class="form-group">
					 <label class="control-label col-sm-2" for="email">Question:</label>
					 <div class="col-sm-10">
					  	<textarea class="form-control" id="inputQuestion" name="question[body]" placeholder="Enter your question here...."></textarea>
					</div> 
				</div>
			  
	      </div>	
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        <button type="Submit" class="btn btn-primary">Submit</button>
	      </div>
	      <% end %>
	    </div>
	  </div>
	</div>

app/views/home/_new_student_form.html.erb
 <div id="addstudentmodal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 id="modalTitle" class="modal-title">Add Student</h4>
                </div>
                <%= form_for :students,url:'/students',html:{class:"form-horizontal"} do %>

                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label for="Name" class="col-sm-3" control-label">Name : </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="Name" placeholder="Name" name="student[Name]">
                            </div>
                        </div>
                       
                        <div class="form-group row">
                          <label for="DOB" class="col-sm-3">DOB:</label>
                              <div class="col-sm-9">
                                <input class="form-control" type="date"  id="DOB" name="student[DOB]">
                              </div>
                        </div>
                        

                         <div class="form-group">
                            <label for="Mobile" class="col-sm-3" control-label>Mobile No:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="Mobile" name="student[Phone_No]">
                            </div>
                        </div>

                         <div class="form-group">
                            <label for="email" class="col-sm-3" control-label>email:</label>
                            <div class="col-sm-9">
                                <input type="email" id="email" name="student[email]" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Courses" class="col-sm-3">Courses:</label>
                            <div class="col-sm-9">
                              <select class="form-control" id="Courses" class="col-sm-9" name="student[course]">
                                <option>JAVA</option>
                                <option>RUBY</option>
                                <option>.net</option>
                              </select>
                          </div>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                   <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="Submit" class="btn btn-primary">Submit</button>
                </div>

                <% end%>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

app/views/home/index.html.erb
<div class="container">
 
 <nav class="navbar ">
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-brand" style="font-size:46px;">Students</span>
    </div>
    <ul class="nav navbar-nav navbar-right">
              <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#addstudentmodal">Add  New Student  </button>
    <!-- <li id="liuserprofile" class="hidden"><a href="#userprofile">Profile</a></li>  -->
  </ul>
  </div>
</nav>



  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
    <% @students.each do |student|%>
      <tr>
        <td><a href="<%= student_path(student)%>"><%= student.Name%></a></td>
        <td><%= student.email%></td>

        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Delete', student_path(student),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <!-- <td> <a href="<%= edit_student_path(student)%>"" class="btn btn-info" role="button" data-toggle="modal" data-target="#editstudentmodal">Edit</a></td> -->
      </tr>
      <tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students Details</title>
    <%= csrf_meta_tags %>
<!-- <link rel="stylesheet" href="/home/amit/Desktop/Rails/studentInf/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     -->

     <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
   <!-- <script src="/home/amit/Desktop/Rails/studentInfo/app/assets/javascripts/bootstrap.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script> -->

  </head>

  <body>
  <!-- NavBAr -->
  <%= render 'home/navbar'%>

 <div class="container">

  		
  
    <%= yield %>

    <!-- Button trigger modal -->
	<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
	  Launch demo modal
	</button> -->

	<!-- Modal -->

	  <%= render 'home/new_student_form'%>

	  <%= render 'home/edit_student_form'%>
	
 </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :post_name %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :post_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.comment %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @post.comment %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/students/edit.html.erb
<%= form_for(@student, :url => {:action => 'update', :id => @student.id}) do %>
  <div class="form-horizontal">
                        <div class="form-group">
                            <label for="Name" class="col-sm-3" control-label">Name : </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="Name" placeholder="Name"
                                value="<%=@student.Name%>"  name="student[Name]">
                            </div>
                        </div>
                       
                        <div class="form-group row">
                          <label for="DOB" class="col-sm-3">DOB:</label>
                              <div class="col-sm-9">
                                <input class="form-control" type="date"  id="DOB" value="<%=@student.DOB%>" name="student[DOB]">
                              </div>
                        </div>
                        

                         <div class="form-group">
                            <label for="Mobile" class="col-sm-3" control-label>Mobile No:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="Mobile" value="<%=@student.Phone_No%>" name="student[Phone_No]">
                            </div>
                        </div>

                         <div class="form-group">
                            <label for="email" class="col-sm-3" control-label>email:</label>
                            <div class="col-sm-9">
                                <input type="email" id="email" class="form-control" value="<%=@student.email%>" name="student[email]">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="Courses" class="col-sm-3">Courses:</label>
                            <div class="col-sm-9">
                              <select class="form-control" id="Courses" class="col-sm-9" value="<%=@student.course%>" name="student[course]">
                                <option>JAVA</option>
                                <option>RUBY</option>
                                <option>.net</option>
                              </select>
                          </div>
                        </div>

                    </div>
 <%= submit_tag("Update Subject") %>
<% end %>

app/views/students/edit.js.erb
//$("#editstudentmodal").html("<%= j render "new"%>");
$('#editstudentmodal').modal('show');

app/views/students/show.html.erb
<div class="row panel panel-success" style="margin-top:2%;">
            <div class="panel-heading lead">
                <div class="row">
                    <div class="col-lg-8 col-md-8"><i class="fa fa-users"></i> <%=@student.Name%> Details: </div>
                    
                </div>
            </div>
            <div class="panel-body">
                            
                
                                                          
              <div class="row">
                  <div class="col-lg-12 col-md-12">

                      <div class="row">
                         

                              <div class="tab-content">
                                  <div id="Summery" class="tab-pane fade in active">

                                    <div class="table-responsive panel">
                                        <table class="table">
                                            <tbody>

                                                    <tr>
                                                        <td class="text-success"><i class="fa fa-user"></i> Email</td>
                                                        <td><%=@student.email%></td>
                                                    </tr>
                                                    <tr>
                                                        <td class="text-success"><i class="fa fa-list-ol"></i> DOB</td>
                                                        <td><%=@student.DOB%></td>
                                                    </tr>
                                                    <tr>
                                                        <td class="text-success"><i class="fa fa-book"></i> Phone_No</td>
                                                        <td><%=@student.Phone_No%></td>
                                                    </tr>
                                                    <tr>
                                                        <td class="text-success"><i class="fa fa-group"></i> Course
                                                        </td>
                                                        <td><%=@student.course%></td>
                                                    </tr>
                                                    
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                              </div>

                          </div>

                      </div>
                  </div>
              </div>
                <!-- /.table-responsive -->
                
            </div>
        </div>